### ISSUE TITLE
python 3.10.6 KeyError: 'cron'

### ISSUE THREAD

**Issue by bbartling** [OpenLEADR/openleadr-python#148]
On Python 3.10.6

does anyone run into this? when just running the 1 minute client example script? Odd thing is this works fine on Windows python 3.10 but on Ubuntu 20.04 I run into this issue...

```
future: <Task finished name='Task-1' coro=<OpenADRClient.run() done, defined at /home/ben/.local/lib/python3.10/site-packages/openleadr/client.py:123> exception=DistributionNotFound(Requirement.parse('funcsigs; python_version < "3.5"'), None)>
Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 900, in _create_plugin_instance
    plugin_cls = class_container[alias]
KeyError: 'cron'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.10/site-packages/openleadr/client.py", line 137, in run
    await self.register_reports(self.reports)
  File "/home/ben/.local/lib/python3.10/site-packages/openleadr/client.py", line 533, in register_reports
    await self.create_report(report_request)
  File "/home/ben/.local/lib/python3.10/site-packages/openleadr/client.py", line 613, in create_report
    job = self.scheduler.add_job(func=callback,
  File "/home/ben/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 424, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/home/ben/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 925, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/home/ben/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 903, in _create_plugin_instance
    plugin_cls = class_container[alias] = plugin_container[alias].load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'funcsigs; python_version < "3.5"' distribution was not found and is required by the application
```

**Comment by bbartling** [comment]
Is anyone else running into this on Python 3.10? @stan-janssen can people attempt a PR to address issues? I run into this on Ubuntu 20.04 LTS trying to run the Open ADR VEN Client code.

**Comment by stan-janssen** [comment]
I cannot reproduce this issue. I'm running Python 3.10 on Ubuntu 20.04 myself and the examples work fine. Have you tried installing openleadr into a new virtual environment to rule out any other conflicting dependencies?

Of course, PRs are always welcome.
