### ISSUE TITLE
RuntimeError: invalid state transition from COMPLETED to AWAIT_CONFIRMATION

### ISSUE THREAD

**Issue by bbartling** [OpenLEADR/openleadr-python#162]
I noticed this in my log files... anything to worry about? Everything seems to be working just fine in my testing on the VEN side. I do have a bunch of asyncio BACnet application processes running but all my tests pass but just notice this error:

```
The number of intervals in the report is now 1
Report will be sent now.
Run time of job "partial (trigger: cron[hour='*', minute='*', second='*/10'], next run at: 2023-11-26 11:50:00 CST)" was missed by 0:00:02.163016
Run time of job "OpenADRClient._poll (trigger: interval[0:00:10], next run at: 2023-11-26 11:50:04 CST)" was missed by 0:00:01.827891
Run time of job "partial (trigger: cron[hour='*', minute='*', second='*/10'], next run at: 2023-11-26 11:50:10 CST)" was missed by 0:00:02.353598
Run time of job "OpenADRClient._poll (trigger: interval[0:00:10], next run at: 2023-11-26 11:50:14 CST)" was missed by 0:00:01.415365
INFO:__main__:DR Sig is: 0.0
INFO:__main__:BACnet DR is: 0.0
INFO:__main__:BACnet Power Meter is: 19569.0
INFO:__main__:BACnet Opt In Status: active
INFO:__main__:Meter Reading is: 19569.0
INFO:__main__:DR Overrides Status is: inactive
INFO:__main__:BACnet Apply Error Status is: inactive
Adding 2023-11-26 17:50:11.661174+00:00, 19569.0 to report
The number of intervals in the report is now 1
Report will be sent now.
DEBUG:__main__:meter_reading <IPv4Address 10.200.200.196> (<ObjectType: analog-input>, 524297) 'present-value'
Run time of job "OpenADRClient._poll (trigger: interval[0:00:10], next run at: 2023-11-26 11:50:24 CST)" was missed by 0:00:07.352459
Request error ServerTimeoutError:Connection timeout to host https://openadr.slipstream.tools/OpenADR2/Simple/2.0b/EiReport
Task exception was never retrieved
future: <Task finished name='Task-468' coro=<ClientSSM.await_confirmation_timeout() done, defined at /home/bbartling/.local/lib/python3.10/site-packages/bacpypes3/appservice.py:836> exception=RuntimeError('invalid state transition from COMPLETED to AWAIT_CONFIRMATION')>
Traceback (most recent call last):
  File "/home/bbartling/.local/lib/python3.10/site-packages/bacpypes3/appservice.py", line 852, in await_confirmation_timeout
    await self.indication(self.segmentAPDU)
  File "/home/bbartling/.local/lib/python3.10/site-packages/bacpypes3/appservice.py", line 536, in indication
    self.set_state(AWAIT_CONFIRMATION, self.apduTimeout)
  File "/home/bbartling/.local/lib/python3.10/site-packages/bacpypes3/appservice.py", line 404, in set_state
    SSM.set_state(self, newState, timer)
  File "/home/bbartling/.local/lib/python3.10/site-packages/bacpypes3/appservice.py", line 216, in set_state
    raise err
RuntimeError: invalid state transition from COMPLETED to AWAIT_CONFIRMATION
```

**Comment by JoelBender** [comment]
This is a timing issue within BACpypes and is only tangentially related to OpenLEADR.  The stack thinks the request has already been "completed" because it timed out, but the task to send out the request was backed up behind something else (probably the call to `OpenADRClient._poll()` so it didn't get its chance to work until the latter timed out.  I don't think this is something to worry about.

**Comment by bbartling** [comment]
ah oh wow Thanks @JoelBender!
