### ISSUE TITLE
How to import OpenSSL.crypto correctly

### ISSUE THREAD

**Issue by ProttayMondalAdhikari-eaton** [OpenLEADR/openleadr-python#177]
I am getting the following error, when I try to compile my custom VEN.py code. 

```
Traceback (most recent call last):
  File "/root/openleadr-python/./pma/VEN.py", line 3, in <module>
    from openleadr import OpenADRClient, enable_default_logging
  File "/usr/local/lib/python3.12/dist-packages/openleadr/__init__.py", line 20, in <module>
    from .client import OpenADRClient
  File "/usr/local/lib/python3.12/dist-packages/openleadr/client.py", line 27, in <module>
    from signxml.exceptions import InvalidSignature
  File "/usr/local/lib/python3.12/dist-packages/signxml/__init__.py", line 7, in <module>
    from .verifier import XMLVerifier, VerifyResult, SignatureConfiguration
  File "/usr/local/lib/python3.12/dist-packages/signxml/verifier.py", line 13, in <module>
    from OpenSSL.crypto import verify as openssl_verify
ImportError: cannot import name 'verify' from 'OpenSSL.crypto' (unknown location)
```

However, if I comment out the following
`from OpenSSL.crypto import verify as openssl_verify `
line from verifier.py, the code goes through

![image](https://github.com/user-attachments/assets/3c64c88f-192a-47e1-ad20-2c466bb6b548)

How do I properly source the OpenSSL.crypto library, so that the verify function can be added? 

The first three lines are getting picked up. Even though they are from the same library. 
![image](https://github.com/user-attachments/assets/8eb9c2dd-2861-45ec-a00c-2df57b002c83)

What am I missing? I am just getting started with this repo.

**Comment by tonsmets** [comment]
I have the same issue (tested on python 3.9, 3.10 and 3.11). I did some searching around and it seems the `pyOpenSSL` package version is the issue. When installing `openleadr` it installs version `pyOpenSSL==23.0.0` (which is already quite old). 

I found [this thread](https://github.com/bellingcat/auto-archiver/issues/155) that suggests updating to `pyOpenSSL==24.2.1` and this seems to have resolved the issue for now.

Maybe we can hardcode this (minimum) `pyOpenSSL` version in https://github.com/OpenLEADR/openleadr-python/blob/main/setup.py?

**Comment by axmsoftware** [comment]
Added pyOpenSSL==24.2.1 on the Workflow action file. Thanks for finding this one out.

**Comment by axmsoftware** [comment]
@tonsmets thank you for helping resolving this issue.
